2017/10/03 00:32:40 [error] [exception.ParseError] ParseError: syntax error, unexpected 'site' (T_STRING), expecting ')' in D:\xampp\htdocs\yiitest\protected\views\layouts\main.php:36
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#1 D:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#2 D:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#3 D:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#4 D:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#5 D:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#6 D:\xampp\htdocs\yiitest\protected\views\layouts\column1.php(6): CBaseController->endContent()
#7 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\\xampp\\htdocs...')
#8 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#9 D:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#10 D:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#11 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#16 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yiitest/index.php?r=site/contact
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:34:25 [error] [exception.ParseError] ParseError: syntax error, unexpected 'site' (T_STRING), expecting ')' in D:\xampp\htdocs\yiitest\protected\views\layouts\main.php:36
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#1 D:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#2 D:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#3 D:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#4 D:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#5 D:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#6 D:\xampp\htdocs\yiitest\protected\views\layouts\column1.php(6): CBaseController->endContent()
#7 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\\xampp\\htdocs...')
#8 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#9 D:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#10 D:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#11 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#16 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yiitest/index.php?r=site/contact
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:35:01 [error] [exception.ParseError] ParseError: syntax error, unexpected ',' in D:\xampp\htdocs\yiitest\protected\views\layouts\main.php:36
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#1 D:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#2 D:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#3 D:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#4 D:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#5 D:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#6 D:\xampp\htdocs\yiitest\protected\views\layouts\column1.php(6): CBaseController->endContent()
#7 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\\xampp\\htdocs...')
#8 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#9 D:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#10 D:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#11 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#16 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yiitest/index.php?r=site/contact
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:35:03 [error] [exception.ParseError] ParseError: syntax error, unexpected ',' in D:\xampp\htdocs\yiitest\protected\views\layouts\main.php:36
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#1 D:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#2 D:\xampp\htdocs\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#3 D:\xampp\htdocs\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#4 D:\xampp\htdocs\yii\framework\web\CBaseController.php(206): COutputProcessor->run()
#5 D:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#6 D:\xampp\htdocs\yiitest\protected\views\layouts\column1.php(6): CBaseController->endContent()
#7 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\\xampp\\htdocs...')
#8 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\\xampp\\htdocs...', Array, true)
#9 D:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('D:\\xampp\\htdocs...', Array, true)
#10 D:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#11 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('contact')
#16 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/yiitest/index.php?r=site/contact
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:35:17 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:35:32 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:37:21 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/page&view=about
---
2017/10/03 00:37:23 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/user
---
2017/10/03 00:37:59 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/user
---
2017/10/03 00:37:59 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/user
---
2017/10/03 00:38:01 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/user
---
2017/10/03 00:38:30 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/user
---
2017/10/03 00:39:16 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/page&view=about
---
2017/10/03 00:41:00 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/index
---
2017/10/03 00:41:19 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/index
---
2017/10/03 00:43:35 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:46:03 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/user
---
2017/10/03 00:48:54 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:52:01 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:52:42 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/03 00:52:44 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/username
---
2017/10/03 00:54:02 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/login
---
2017/10/03 00:54:43 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/login
---
2017/10/03 00:54:45 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/username
---
2017/10/03 00:54:46 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/username
---
2017/10/03 00:54:46 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/username
---
2017/10/03 00:55:53 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/username
---
2017/10/03 00:55:53 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/username
---
2017/10/03 00:55:54 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/username
---
2017/10/03 00:55:54 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "username". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('username')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('username')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/username')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/username
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/username
---
2017/10/03 00:55:56 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/login
---
2017/10/03 00:56:18 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/login
---
2017/10/03 00:56:19 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/login
---
2017/10/03 00:56:19 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/login
---
2017/10/03 00:59:10 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "user". in D:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/user')
#3 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/yiitest/index.php?r=site/user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/login
---
2017/10/03 01:31:09 [error] [php] Undefined variable: form (D:\xampp\htdocs\yiitest\protected\views\site\login.php:22)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 D:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 D:\xampp\htdocs\yiitest\protected\controllers\SiteController.php(98): SiteController->render()
#3 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=site/login
in D:\xampp\htdocs\yiitest\protected\views\site\login.php (22)
in D:\xampp\htdocs\yiitest\protected\controllers\SiteController.php (98)
in D:\xampp\htdocs\yiitest\index.php (13)
2017/10/04 19:56:26 [error] [php] require_once(connectDB.php): failed to open stream: No such file or directory (D:\xampp\htdocs\yiitest\protected\views\site\pages\about.php:17)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#1 D:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#3 D:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#4 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#7 D:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=site/page&view=about
in D:\xampp\htdocs\yiitest\protected\views\site\pages\about.php (17)
in D:\xampp\htdocs\yiitest\protected\views\site\pages\about.php (17)
in D:\xampp\htdocs\yiitest\index.php (13)
2017/10/04 21:04:34 [error] [exception.CHttpException.404] CHttpException: The requested view "user" was not found. in D:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('user')
#1 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yiitest/index.php?r=site/page&view=user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/page&view=about
---
2017/10/05 07:54:58 [error] [exception.CHttpException.404] CHttpException: The requested view "user" was not found. in D:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('user')
#1 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yiitest/index.php?r=site/page&view=user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/login
---
2017/10/05 08:00:06 [error] [exception.CHttpException.404] CHttpException: The requested view "user" was not found. in D:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('user')
#1 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/yiitest/index.php?r=site/page&view=user
HTTP_REFERER=http://localhost:81/yiitest/index.php?r=site/contact
---
2017/10/05 08:28:34 [error] [php] Undefined variable: content (D:\xampp\htdocs\yiitest\protected\views\greeting\index.php:9)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(869): GreetingController->renderFile()
#1 D:\xampp\htdocs\yii\framework\web\CController.php(782): GreetingController->renderPartial()
#2 D:\xampp\htdocs\yiitest\protected\controllers\GreetingController.php(8): GreetingController->render()
#3 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): GreetingController->actionIndex()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(286): GreetingController->runAction()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): GreetingController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): GreetingController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php?r=greeting
in D:\xampp\htdocs\yiitest\protected\views\greeting\index.php (9)
in D:\xampp\htdocs\yiitest\protected\controllers\GreetingController.php (8)
in D:\xampp\htdocs\yiitest\index.php (13)
2017/10/05 09:00:29 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 D:\xampp\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 D:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yiitest/index.php/gii/model/index
HTTP_REFERER=http://localhost:81/yiitest/index.php/gii/default/index
---
2017/10/05 10:53:01 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gretting/index". in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gretting/index')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php/gretting/index?view=index
HTTP_REFERER=http://localhost:81/yiitest/index.php/user/admin
---
2017/10/05 10:55:06 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gretting/index". in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gretting/index')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php/gretting/index?view=index
HTTP_REFERER=http://localhost:81/yiitest/index.php/user/admin
---
2017/10/05 10:55:08 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gretting/index". in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gretting/index')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php/gretting/index?view=index
HTTP_REFERER=http://localhost:81/yiitest/index.php/user/admin
---
2017/10/05 10:55:17 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gretting/index". in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gretting/index')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php/gretting/index?view=index
HTTP_REFERER=http://localhost:81/yiitest/index.php/user/admin
---
2017/10/05 10:55:18 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gretting/index". in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gretting/index')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/yiitest/index.php/gretting/index?view=index
HTTP_REFERER=http://localhost:81/yiitest/index.php/user/admin
---
2017/10/06 08:57:04 [error] [php] A non-numeric value encountered (D:\xampp\htdocs\yiitest\protected\views\user\view.php:25)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(869): UserController->renderFile()
#1 D:\xampp\htdocs\yii\framework\web\CController.php(782): UserController->renderPartial()
#2 D:\xampp\htdocs\yiitest\protected\controllers\UserController.php(55): UserController->render()
#3 unknown(0): UserController->actionView()
#4 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#5 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#8 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#10 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#11 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#13 D:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php/user/5
in D:\xampp\htdocs\yiitest\protected\views\user\view.php (25)
in D:\xampp\htdocs\yiitest\protected\controllers\UserController.php (55)
in D:\xampp\htdocs\yiitest\index.php (13)
2017/10/06 09:07:57 [error] [exception.ParseError] ParseError: syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in D:\xampp\htdocs\yiitest\protected\controllers\UserController.php:75
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(276): CWebApplication->createController('create/')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#2 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#3 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#4 {main}
REQUEST_URI=/yiitest/index.php/user/create
HTTP_REFERER=http://localhost:81/yiitest/index.php/user/admin
---
2017/10/06 09:09:53 [error] [exception.ParseError] ParseError: syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in D:\xampp\htdocs\yiitest\protected\controllers\UserController.php:100
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(276): CWebApplication->createController('create/')
#1 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/create')
#2 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#3 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#4 {main}
REQUEST_URI=/yiitest/index.php/user/create
HTTP_REFERER=http://localhost:81/yiitest/index.php/user/create
---
2017/10/06 09:23:08 [error] [php] A non-numeric value encountered (D:\xampp\htdocs\yiitest\protected\models\User.php:58)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\validators\CRequiredValidator.php(71): CRequiredValidator->addError()
#1 D:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CRequiredValidator->validateAttribute()
#2 D:\xampp\htdocs\yii\framework\base\CModel.php(159): CRequiredValidator->validate()
#3 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(805): User->validate()
#4 D:\xampp\htdocs\yiitest\protected\controllers\UserController.php(73): User->save()
#5 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UserController->actionCreate()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UserController->runAction()
#8 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#9 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#10 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UserController->filterAccessControl()
#11 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#13 D:\xampp\htdocs\yii\framework\web\CController.php(265): UserController->runActionWithFilters()
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UserController->run()
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\xampp\htdocs\yiitest\index.php(13): CWebApplication->run()
REQUEST_URI=/yiitest/index.php/user/create
in D:\xampp\htdocs\yiitest\protected\models\User.php (58)
in D:\xampp\htdocs\yiitest\protected\controllers\UserController.php (73)
in D:\xampp\htdocs\yiitest\index.php (13)
2017/10/06 09:23:24 [error] [exception.CHttpException.400] CHttpException: Your request is invalid. in D:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/view')
#10 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\xampp\htdocs\yiitest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/yiitest/index.php/user/view?name=
HTTP_REFERER=http://localhost:81/yiitest/index.php/user/create
---
